blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://github.com/ArabCoders/watchstate/discussions
    about: Please use the discussions tab for features or enhancements requests.
  - name: Questions & Answers
    url: https://github.com/ArabCoders/watchstate/discussions
    about: Please use the discussions tab for questions.
