name: Generate Changelog

on:
  push:
    tags:
      - "*"  # Trigger on any tag push

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure we get all tags and history

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gitpython

      - name: Get Branch Name from Tag
        id: branch_name
        run: |
          TAG_NAME=$(git describe --tags --abbrev=0)
          BRANCH_NAME=$(echo "$TAG_NAME" | cut -d '-' -f1)
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "Detected Tag: $TAG_NAME on Branch: $BRANCH_NAME"

      - name: Generate Changelog JSON
        run: |
          python .github/scripts/generate_changelog.py --repo_path . --changelog_path ./CHANGELOG-${BRANCH_NAME}.json --branch_name $BRANCH_NAME

      - name: Commit and Push to GitHub Pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout gh-pages || git checkout --orphan gh-pages
          git pull origin gh-pages || true
          mv CHANGELOG-*.json .
          git add CHANGELOG-*.json
          git commit -m "Update Changelog for $TAG_NAME"
          git push origin gh-pages
